// SEARCH LOCATION

export const MARKER_SEARCH_CHANGE = "MARKER_SEARCH_CHANGE";
export const REGION_SEARCH_CHANGE = "REGION_SEARCH_CHANGE";
export const STREET_SEARCH_CHANGE = "STREET_SEARCH_CHANGE";
