// SEARCH LOCATION

export const MARKER_SEARCH_CHANGE = "MARKER_SEARCH_CHANGE";
export const REGION_SEARCH_CHANGE = "REGION_SEARCH_CHANGE";
export const STREET_SEARCH_CHANGE = "STREET_SEARCH_CHANGE";
export const PERSON_SEARCH_CHANGE = "PERSON_SEARCH_CHANGE";

// Bookmark
export const BOOKMARK_CHANGE = "BOOKMARK_CHANGE";
export const BOOKMARK_LOADED_CHANGE = "BOOKMARK_LOADED_CHANGE";

// tracking
export const JOURNEY_RESET = "JOURNEY_RESET";
export const FETCH_JOURNEY_LIST = "FETCH_JOURNEY_LIST";
export const TRACKING_STATUS_CHANGE = "TRACKING_STATUS_CHANGE";
export const CURRENT_JOURNEY_NAME_CHANGE = "CURRENT_JOURNEY_NAME_CHANGE";
export const CURRENT_JOURNEY_POINTS_LIST_CHANGE =
  "CURRENT_JOURNEY_POINTS_LIST_CHANGE";
