// SEARCH LOCATION

export const MARKER_SEARCH_CHANGE = "MARKER_SEARCH_CHANGE";
export const REGION_SEARCH_CHANGE = "REGION_SEARCH_CHANGE";
export const STREET_SEARCH_CHANGE = "STREET_SEARCH_CHANGE";
export const PERSON_SEARCH_CHANGE = "PERSON_SEARCH_CHANGE";

// Bookmark
export const BOOKMARK_CHANGE = "BOOKMARK_CHANGE";
export const BOOKMARK_LOADED_CHANGE = "BOOKMARK_LOADED_CHANGE";
